workflows update

diff --git a/.github/workflows/helm_deploy.yml b/.github/workflows/helm_deploy.yml
--- a/.github/workflows/helm_deploy.yml
+++ b/.github/workflows/helm_deploy.yml
@@ -34,78 +34,52 @@ jobs:
           source: 'deploy/helm,deploy/kubectl'
           target: ${{ secrets.CICD_PATH }}/
       
-#      # helm upgrade --> install
-#      - name: SSH Remote Commands from ci/cd server
-#        uses: garygrossgarten/github-action-ssh@release
-#        with:
-#          host: ${{ secrets.CICD_HOST }}
-#          username: ${{ secrets.CICD_USER }}
-#          password: ${{ secrets.CICD_PASS }}
-#          command: |
-#            cd ${{ secrets.CICD_PATH }}/deploy/helm
-#
-#            if [ -e "./values-prod-custom.yaml" ]; then
-#              echo "Custom values-prod-custom.yaml found. Running prod-deploy.sh..."
-#              sh prod-deploy.sh
-#
-#              if [ $? -ne 0 ]; then
-#                echo "prod-deploy.sh failed. Falling back to inline Helm deployment."
-#                run_inline_helm_deploy=true
-#              else
-#                run_inline_helm_deploy=false
-#              fi
-#            else
-#              echo "values-prod-custom.yaml not found. Proceeding with inline Helm deployment."
-#              run_inline_helm_deploy=true
-#            fi
-#
-#            if [ "$run_inline_helm_deploy" = true ]; then
-#              kubectl apply -f ../kubectl/class-roles
-#
-#              if ! helm repo list | grep -q 'nfs-subdir-external-provisioner'; then
-#                helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
-#              fi
-#              if ! helm status nfs-subdir-external-provisioner -n kube-system >/dev/null 2>&1; then
-#                 helm upgrade --install nfs-subdir-external-provisioner \
-#                   nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
-#                     -n kube-system \
-#                     --set nfs.server=${{ secrets.CICD_HOST }} \
-#                     --set nfs.path=/mnt/nfs-subdir-external-provisioner
-#              fi
-#
-#              helm upgrade ${{ secrets.DATABASE_USER }} . -f ./values-prod.yaml \
-#                --install -n ibs-prod --create-namespace --history-max 5 --wait --timeout 10m \
-#                --set global.dbPassword=${{ secrets.DATABASE_PASS }} \
-#                --set global.cicdServerHost=${{ secrets.CICD_HOST }} \
-#                --set global.cicdPath=${{ secrets.CICD_PATH }} \
-#                --set global.nfsServerHost=${{ secrets.NFS_HOST }} \
-#                --set global.nfsPath=${{ secrets.NFS_PATH }} \
-#                --set global.domainHost=${{ secrets.DOMAIN_HOST }} \
-#                --set global.emailHost=${{ secrets.EMAIL_HOST }} \
-#                --set global.emailHostUser=${{ secrets.EMAIL_HOST_USER }} \
-#                --set-string global.emailHostPassword='${{ secrets.EMAIL_HOST_PASSWORD }}' \
-#                --set global.defaultFromEmail=${{ secrets.EMAIL_DEFAULT_FROM }} \
-#                --set postgres.auth.postgresPassword=${{ secrets.DATABASE_PASS }} \
-#                --set postgres.auth.password=${{ secrets.DATABASE_PASS }} \
-#                --set postgres.auth.replicationPassword=${{ secrets.DATABASE_PASS }} \
-#                --set 'nginx.ingress.hosts[0].host'=${{ secrets.DOMAIN_NAME }} \
-#                --set 'nginx.ingress.hosts[1].host'=www.${{ secrets.DOMAIN_NAME }} \
-#                --set 'nginx.ingress.hosts[2].host'=dyibs.co.kr \
-#                --set 'nginx.ingress.hosts[3].host'=brdnc.co.kr \
-#                --set 'nginx.ingress.hosts[0].paths[0].path'=/ \
-#                --set 'nginx.ingress.hosts[0].paths[0].pathType'=Prefix \
-#                --set 'nginx.ingress.hosts[1].paths[0].path'=/ \
-#                --set 'nginx.ingress.hosts[1].paths[0].pathType'=Prefix \
-#                --set 'nginx.ingress.hosts[2].paths[0].path'=/ \
-#                --set 'nginx.ingress.hosts[2].paths[0].pathType'=Prefix \
-#                --set 'nginx.ingress.hosts[3].paths[0].path'=/ \
-#                --set 'nginx.ingress.hosts[3].paths[0].pathType'=Prefix \
-#                --set 'nginx.ingress.tls[0].hosts[0]'=${{ secrets.DOMAIN_NAME }} \
-#                --set 'nginx.ingress.tls[0].hosts[1]'=www.${{ secrets.DOMAIN_NAME }} \
-#                --set 'nginx.ingress.tls[0].hosts[2]'=dyibs.co.kr \
-#                --set 'nginx.ingress.tls[0].hosts[3]'=brdnc.co.kr \
-#                --set 'nginx.ingress.tls[0].secretName'=web-devbox-kr-cert
-#            fi
+      # helm upgrade --> install
+      - name: SSH Remote Commands from ci/cd server
+        uses: garygrossgarten/github-action-ssh@release
+        with:
+          host: ${{ secrets.CICD_HOST }}
+          username: ${{ secrets.CICD_USER }}
+          password: ${{ secrets.CICD_PASS }}
+          command: |
+            cd ${{ secrets.CICD_PATH }}/deploy/helm
+
+            if [ -e "./values.yaml" ]; then
+              echo "values.yaml found. Running deploy.sh..."
+              sh deploy.sh
+
+              if [ $? -ne 0 ]; then
+                echo "deploy.sh failed. Falling back to inline Helm deployment."
+                run_inline_helm_deploy=true
+              else
+                run_inline_helm_deploy=false
+              fi
+            else
+              echo "values.yaml not found. Proceeding with inline Helm deployment."
+              run_inline_helm_deploy=true
+            fi
+
+            if [ "$run_inline_helm_deploy" = true ]; then
+              kubectl apply -f ../kubectl
+
+              if ! helm repo list | grep -q 'nfs-subdir-external-provisioner'; then
+                helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
+              fi
+              if ! helm status rhymix-nfs-subdir-external-provisioner -n kube-system >/dev/null 2>&1; then
+                helm upgrade --install rhymix nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
+                  -n kube-system \
+                  --set nfs.server=${{ secrets.NFS_HOST }} \
+                  --set nfs.path=${{ secrets.NFS_PATH }}/volume/data \
+                  --set storageClass.name=nfs-rhymix
+              fi
+
+              # Role 적용 및 Helm 배포
+              kubectl apply -f ../kubectl/cluster-role.yaml
+              helm upgrade rhymix . -f ./values.yaml \
+                --install -n rhymix --create-namespace --history-max 5 --wait --timeout 10m \
+                --set mariadb.auth.rootPassword=${{ secrets.MARIADB_PASSWORD }} \
+                --set mariadb.auth.password=${{ secrets.MARIADB_PASSWORD }}
+            fi
       
       # slack --> notification
       - name: Send slack when failed
